<?php if ($this->CssClass() || $this->CssID()):?>
<div<?php if ($this->CssClass()): ?> class="<?php HtmlOut($this->CssClass())?>"<?php endif; ?><?php if ($this->CssID()):?> id="<?php HtmlOut($this->CssID())?>"<?php endif; ?>>
<?php endif; ?>
<?php if ($this->success): ?>
<div class="alert-box success">
    <?php echo Trans('BuiltIn.ChangePasswordConfirm.Success'); ?>
</div>
<?php elseif (!$this->isValid): ?>
<div class="alert-box alert">
    <?php echo Trans('BuiltIn.ChangePasswordConfirm.Error'); ?>
</div>
<?php else: ?>
    <form action="<?php HtmlOut(CurrentUri()); ?>" method="post">
        <?php echo $this->RenderElement('Password'); ?>
        <?php echo $this->RenderElement('PasswordRepeat'); ?>
        <?php echo $this->RenderSubmit(); ?>
    </form>
<?php endif; ?>
<?php if ($this->CssClass() || $this->CssID()):?>
</div>
<?php endif; ?>
