<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back')?>"></a><?php TransOut('BuiltIn.ChangePasswordConfirmForm.Title') ?></h1>
<p>
    <?php TransOut('BuiltIn.ChangePasswordConfirmForm.Description') ?>
</p>
<form method="post" action="<?php HtmlOut(CurrentUri()) ?>">
    <fieldset>
        <legend><?php TransOut('BuiltIn.ChangePasswordConfirmForm.Legend') ?></legend>
        <?php echo $this->selectorSuccess->Render(); ?>
        <?php echo $this->selectorError->Render(); ?>
        <div class="row">
            <div class="medium-4 columns">
                <?php echo $this->RenderElement('CssID'); ?>
            </div>
            <div class="medium-4 columns">
                <?php echo $this->RenderElement('CssClass'); ?>
            </div>
            <div class="medium-4 columns">
                <?php echo $this->RenderElement('Template'); ?>
            </div>
        </div>
    </fieldset>
    <?php echo $this->RenderWordingFields(); ?>
    <?php echo $this->RenderAccessElements(); ?>
    <?php echo $this->RenderSubmit(); ?>
</form>