<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back')?>"></a><?php TransOut('BuiltIn.NavigationItemForm.Title') ?></h1>
<p>
    <?php TransOut('BuiltIn.NavigationItemForm.Description') ?>
</p>
<form method="post" action="<?php HtmlOut(CurrentUri()) ?>">
    <fieldset>
        <legend><?php TransOut('BuiltIn.NavigationItemForm.Legend') ?></legend>
        <div class="row">
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('Type'); ?>
            </div>
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('Name'); ?>
            </div>
        </div>
        <div id="UrlFields">
            <div class="row">
                <div class="medium-12 columns">
                    <?php echo $this->RenderElement('Url'); ?>
                </div>
            </div>
        </div>
        <div id="PageFields">
            <div class="row">
                <div class="medium-12 columns">
                    <?php echo $this->selector->Render(); ?>
                </div>
            </div>
        </div>
    </fieldset>
    <?php echo $this->RenderSubmit(); ?>
</form>