<h1><a href="<?php HtmlOut($this->BackLink()) ?>" class="fa fa-chevron-circle-left right" title="<?php TransOut('Core.ButtonText.Back')?>"></a><?php TransOut('BuiltIn.NavigationForm.Title') ?></h1>
<p>
    <?php TransOut('BuiltIn.NavigationForm.Description') ?>
</p>
<form method="post" action="<?php HtmlOut(CurrentUri()) ?>">
    <fieldset>
        <legend><?php TransOut('BuiltIn.NavigationForm.Legend') ?></legend>
        <div class="row">
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('Name'); ?>
            </div>
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('Template'); ?>
            </div>
        </div>
        <div class="row">
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('CssID'); ?>
            </div>
            <div class="medium-6 columns">
                <?php echo $this->RenderElement('CssClass'); ?>
            </div>
        </div>
        <div class="row">
            <div class="medium-12 columns">
                <?php echo $this->RenderElement('CacheLifetime'); ?>
            </div>
        </div>
    </fieldset>
    <?php echo $this->RenderAccessElements(); ?>
    <?php echo $this->RenderSubmit(); ?>
</form>